### ISSUE TITLE
DMF_VirtualHidKeyboard

### ISSUE THREAD

**Issue by TronicLabs** [Microsoft/DMF#15]
This example module is missing?

**Comment by hansmbakker** [comment]
I believe they replaced it with https://github.com/Microsoft/DMF/blob/master/Dmf/Modules.Library/Dmf_HidPortableDeviceButtons.txt

**Comment by samtertzakian** [comment]
DMF_HidPortableDeviceButtons is an example of how to make a Virtual HID device. But, it does not replace the DMF_VirtualHidKeyboard. I will investigate this and update here.

**Comment by samtertzakian** [comment]
I have just submitted a fix for this.
