### ISSUE TITLE
Debugging assertion in DMF\Dmf\Modules.Library\Dmf_ScheduledTask.c

### ISSUE THREAD

**Issue by alkovacs** [microsoft/DMF#173]
Don't know what the issue is as of yet, still debugging. So far found...
****
DMF\Dmf\Modules.Library\Dmf_ScheduledTask.md
will execute neither in during PrepareHardware nor D0Exntry. **(Is this Exit or Entry, or Both)**

DMF\Dmf\Modules.Library\Dmf_ScheduledTask.c
if (moduleConfig->ExecuteWhen == ScheduledTask_ExecuteWhen_Other)
{
    TraceEvents(TRACE_LEVEL_INFORMATION, DMF_TRACE, "Set ModuleClosing");
    moduleContext->ModuleClosing = TRUE;
}
DMF\Dmf\Modules.Library\Dmf_ScheduledTask.c
// Stop the timer and wait for any pending call to finish.
//
DmfAssert(moduleContext->ModuleClosing);  **(Hitting this assertion)**
WdfTimerStop(moduleContext->Timer,
             TRUE);

DMF\Dmf\Modules.Library\Dmf_QueuedWorkItem.c
scheduledTaskConfig.ExecuteWhen = ScheduledTask_ExecuteWhen_Other;

DMF\Dmf\Modules.Library.Tests\Dmf_Tests_ScheduledTask.c
if (taskDescription->ExecuteWhen != ScheduledTask_ExecuteWhen_Other)
{
    continue;
}

**Comment by alkovacs** [comment]
<img width="960" alt="Debug 1" src="https://user-images.githubusercontent.com/22898659/123996556-11fbc800-d995-11eb-9763-6b150bf4079f.png">

**Comment by alkovacs** [comment]
<img width="960" alt="Debug 2" src="https://user-images.githubusercontent.com/22898659/123998601-42446600-d997-11eb-8f3d-51cb7eeb76dd.png">

**Comment by alkovacs** [comment]
So when I unload the device, it seems to hit this code 3 times, the first 2 (second image) when moduleConfig->ExecuteWhen is set to ScheduledTask_ExecuteWhen_Invalid and the assertion is made. On the third pass when moduleConfig->ExecuteWhen is set to  ScheduledTask_ExecuteWhen_Other (first image) the assertion is not made as ModuleClosing gets set. There are 2 instances of the device loaded.

**Comment by samtertzakian** [comment]
The fact that ExecuteWhen is set to "Invalid" tells me that something is wrong. It seems like the callback is executing very late...much later than it should (an that the memory for the object has already been deleted). 

Are you instantiating DMF_QueuedWorkitem which uses ScheduledTask as Child Module? Are you instantiating it statically (In ModulesAdd() callback) or dynamically using DMF_QueuedWorkitem_Create().

If dynamically, how are you setting the parent of the Module using WDF_OBJECT_ATTRIBUTES()?

Something is definitely wrong and this error should be fixed. 

As for your questions above, what applies to D0Entry also applies to D0Exit. I will clarify documentation about this.

**Comment by alkovacs** [comment]
Hi Sam! Thanks for getting back to me so quickly. DMF_QueuedWorkitem is NOT being called in the driver code, should it be?

**Comment by alkovacs** [comment]
Also, in the Init() function, we are calling:
`WDF_OBJECT_ATTRIBUTES lockAttributes;
		WDF_OBJECT_ATTRIBUTES_INIT(&lockAttributes);
		status = WdfWaitLockCreate(&lockAttributes, &m_CodecPowerLock);`

**Comment by samtertzakian** [comment]
> Hi Sam! Thanks for getting back to me so quickly. DMF_QueuedWorkitem is NOT being called in the driver code, should it be?

Can you tell me what Modules you are instantiating and how you are instantiating them?

Two ways are:
1. Static (in ModulesAdd() callback which is called during DeviceAdd).
2. Dynamically (using DMF_[ModuleName]_Create which can be called anywhere in the driver).

> Also, in the Init() function, we are calling:
> `WDF_OBJECT_ATTRIBUTES lockAttributes; WDF_OBJECT_ATTRIBUTES_INIT(&lockAttributes); status = WdfWaitLockCreate(&lockAttributes, &m_CodecPowerLock);`

This is not the object attributes that I was talking about. Also, you are initializing object attributes but not setting the parent object afterward. I was asking about the WDF_OBJECT_ATTRIBUTES you use for the DMF Module.

My feeling is you might be using a Module as global variable or doing something funky like that. Let me know what Modules you instantiate and how (and where)?

**Comment by alkovacs** [comment]
@samtertzakian 
### So the modules are added in ModulesAdd().
###  But I am seeing some strangeness here... (I have inherited this code, it was said to be "almost working"!)
### So first (order encountered in code) this is being done...

`#ifdef __cplusplus
extern "C" {
#endif

    DRIVER_INITIALIZE DriverEntry;
    EVT_WDF_DRIVER_DEVICE_ADD ourDriverEvtDeviceAdd;
    EVT_WDF_OBJECT_CONTEXT_CLEANUP ourDriverEvtDriverContextCleanup;
    EVT_DMF_DEVICE_MODULES_ADD ourDriverDmfModulesAdd;
    EVT_WDF_DEVICE_PREPARE_HARDWARE ourDriverEvtDevicePrepareHardware;
    EVT_WDF_DEVICE_RELEASE_HARDWARE ourDriverEvtDeviceReleaseHardware;
    EVT_WDF_DEVICE_D0_ENTRY ourDriverEvtDeviceD0Entry;
    EVT_WDF_DEVICE_D0_EXIT ourDriverEvtDeviceD0Exit;
    EVT_DMF_IoctlHandler_Callback ourDriverIoDeviceControl;
#ifdef __cplusplus
}
#endif`

### Then, this is being done ...
`  // DMF: Initialize the DMF_EVENT_CALLBACKS to set the callback DMF will call
   // to get the list of Modules to instantiate.
  
    DMF_EVENT_CALLBACKS_INIT(&dmfEventCallbacks);
    dmfEventCallbacks.EvtDmfDeviceModulesAdd = ourDriverDmfModulesAdd;
    DMF_DmfDeviceInitSetEventCallbacks(dmfDeviceInit,  &dmfEventCallbacks);`

### And in the **ourDriverDmfModulesAdd** (honestly I have not yet had the chance to debug the Dmf => WDF interfaces)...

`_IRQL_requires_max_(PASSIVE_LEVEL)
VOID
ourDriverDmfModulesAdd(
_In_ WDFDEVICE Device,
_In_ PDMFMODULE_INIT DmfModuleInit
)
{
    TraceEvents(TRACE_LEVEL_INFORMATION, DBG_PNP, "--> %s\n", __FUNCDNAME__);

    DMF_MODULE_ATTRIBUTES moduleAttributes;
    DMF_CONFIG_IoctlHandler moduleConfigIoctlHandler;
    DMF_CONFIG_DeviceInterfaceTarget moduleConfigDeviceInterfaceTarget;
    DMF_CONFIG_ScheduledTask moduleConfigScheduledTask;

    DEVICE_CONTEXT* pDevContext;

    pDevContext = GetDeviceContext(Device);

    // interface IoctlHandler
    DMF_CONFIG_IoctlHandler_AND_ATTRIBUTES_INIT(&moduleConfigIoctlHandler, &moduleAttributes);
    moduleConfigIoctlHandler.DeviceInterfaceGuid = OUR_INTERFACE_GUID;
    moduleConfigIoctlHandler.IoctlRecords = ourDriverIfcIoctlHandlerTable;
    moduleConfigIoctlHandler.IoctlRecordCount = _countof(ourDriverIfcIoctlHandlerTable);
    moduleConfigIoctlHandler.ManualMode = TRUE;
    DMF_DmfModuleAdd(DmfModuleInit, &moduleAttributes, WDF_NO_OBJECT_ATTRIBUTES, &pDevContext->DmfModuleourDriverIfcIoctlHandler);

    // interface request target
    DMF_CONFIG_DeviceInterfaceTarget_AND_ATTRIBUTES_INIT(&moduleConfigDeviceInterfaceTarget, &moduleAttributes);
    moduleConfigDeviceInterfaceTarget.DeviceInterfaceTargetGuid = OUR_INTERFACE_GUID;
    moduleConfigDeviceInterfaceTarget.EvtDeviceInterfaceTargetOnStateChange = ourDriverInterfaceTarget_OnStateChange;
    moduleConfigDeviceInterfaceTarget.EvtDeviceInterfaceTargetOnPnpNotification = ourDriverInterfaceTarget_OnPnpNotification;
    DMF_DmfModuleAdd(DmfModuleInit, &moduleAttributes, WDF_NO_OBJECT_ATTRIBUTES, &pDevContext->DmfModuleourDriverIfcRequestTarget);

    // interface arrival task
    DMF_CONFIG_ScheduledTask_AND_ATTRIBUTES_INIT(&moduleConfigScheduledTask, &moduleAttributes);
    moduleConfigScheduledTask.CallbackContext = pDevContext;
    moduleConfigScheduledTask.EvtScheduledTaskCallback = ourDriverInterfaceArrivalTask;
    DMF_DmfModuleAdd(DmfModuleInit, &moduleAttributes, WDF_NO_OBJECT_ATTRIBUTES, &pDevContext->DmfModuleourDriverInterfaceArrivalTask);

    // interface removal task
    DMF_CONFIG_ScheduledTask_AND_ATTRIBUTES_INIT(&moduleConfigScheduledTask, &moduleAttributes);
    moduleConfigScheduledTask.CallbackContext = pDevContext;
    moduleConfigScheduledTask.EvtScheduledTaskCallback = ourDriverInterfaceRemovalTask;
    moduleConfigScheduledTask.ExecuteWhen = ScheduledTask_ExecuteWhen_Other;  ****// I ADDED THIS AND IT DOES cut the number of assertions detailed previously down to 1 from 2 WHOOPIEEEE! **** 
    DMF_DmfModuleAdd(DmfModuleInit, &moduleAttributes, WDF_NO_OBJECT_ATTRIBUTES, &pDevContext->DmfModuleourDriverInterfaceRemovalTask);

    TraceEvents(TRACE_LEVEL_INFORMATION, DBG_PNP, "<-- %s\n", __FUNCDNAME__);
}`

**Comment by samtertzakian** [comment]
Ok, the good news is you are not doing anything funky! What you are doing is correct. However, I think all you need to do is:

Add this line:
moduleConfigScheduledTask.ExecuteWhen = ScheduledTask_ExecuteWhen_Other;  ****// I ADDED THIS AND IT DOES cut the number of assertions detailed previously down to 1 from 2 WHOOPIEEEE! **** 

To the above instantiation for // interface arrival task. just above (for &pDevContext->DmfModuleourDriverInterface**Arrival**Task)

It cannot be set to zero. You have two instances and you did it for second instance but not first.

Can you try that and let me know....

**Comment by alkovacs** [comment]
@samtertzakian   Thanks Sam! That resolved the issue, should I set values for the other members that are xxx_Invalid ?

<img width="479" alt="Debug 3" src="https://user-images.githubusercontent.com/22898659/124303970-b104f900-db28-11eb-8616-2e31c1749090.png">

**Comment by samtertzakian** [comment]
No you don't need to when ExecutionMode = ScheduledTask_ExecuteWhen_Other.

Unfortunately this Module's interface is not great. It is a very old Module that was updated a few times. We are planning on making an updated version of this Module with a clearer interface. ScheduledTask is only really used when we want to perform an operation a single time. Instead of using ScheduledTask, it is better to use QueuedWorkitem.

One more thing...Are you scheduling work using ScheduledTask from the Arrival/Removal callback? Because, it is almost certain that you can do the work you need to in the callback directly. You probably don't need to use ScheduledTask at all. Whatever work you are doing in *ourDriverInterfaceArrivalTask*, you should be able to do in *ourDriverInterfaceTarget_OnStateChange*.

Can you try that and let me know?

**Comment by samtertzakian** [comment]
Closing issue for now as it appears to be resolved.
