### ISSUE TITLE
Duplicated lines

### ISSUE THREAD

**Issue by DJm00n** [microsoft/DMF#209]
Remove duplicated lines at:

https://github.com/microsoft/DMF/blob/0dc1b70d2604e6ac4c0cb88d36476a8b2c17e9c5/Dmf/Modules.Library/Dmf_VirtualHidDeviceVhf.h#L1140-L1152

**Comment by samtertzakian** [comment]
Looking into this. Thank you.

**Comment by samtertzakian** [comment]
The clean up of the duplicate lines is in the pipeline and should be merged here middle of next month. Thank you!
It will be in Release v1.1.119.
