### ISSUE TITLE
Ambient light sensor documentation contains documentation for keyboard

### ISSUE THREAD

**Issue by hansmbakker** [Microsoft/DMF#31]
https://github.com/Microsoft/DMF/blob/master/Dmf/Modules.Library/Dmf_VirtualHidAmbientLightSensor.md and https://github.com/Microsoft/DMF/blob/master/Dmf/Modules.Library/Dmf_VirtualAmbientLightSensor.mdcontain documentation from the virtual hid keyboard.

**Comment by samtertzakian** [comment]
These issues are now resolved in Release v1.0.9.
Thank you for pointing them out.
