### ISSUE TITLE
manual made project files for a software driver?

### ISSUE THREAD

**Issue by AraHaan** [microsoft/DMF#71]
Is there any way to manually create a project file for a software driver I want to write when my device does not have internet to make the wdf installer work?

What do I need to do you ask? Well for my program it is a need to filter the threads by a list of handles I pass in (``std::vector<HANDLE>``) to a function I want exported and then imported to a function to filter if it is a system made or user made thread. Then if they are then return the # of user made threads in that list. I would also like in that driver also be able to detect when (if the application asks) whenever some other process calls CreateRemoteThread using the handle to the process for means of deploying an registered callback from within the driver to the application.

Edit: Why does kernel32 not have a function for that system / user thread distinction for user mode applications in case they want to do that so they can avoid all this ``software driver`` hackery or even a way for applications to see if they even want the thread from a call to CreateRemoteThread from another process too then if not have the application tell the function no; and make it error with an unauthorized error code from the caller (the other process in this case)?

And yes; I get you need backwards compat then; but then you can do an api call to turn on the new stuff for the process wide only then am I right and have it check some sort of list to see if the process subscribed to it. no?
So maybe something to list that needs done:
1. Ways to filter between system (kernel made) threads / user (application made) threads without needing any sort of drivers.
2. A way to update CreateRemoteThread that can allow the application to decide if it wants the thread if the handle from GetCurrentProcess() != input handle on the call. If not make the function return an error code that represents "unauthorized".
3. A way to subscribe to (2.) on this list by introducing another function that adds the current process to a list then CreateRemoteThread looks to see if it is before doing the updated behavior to prevent breaking existing applications. Maybe in that function it could just be some sort of callback registration function that uses the handle to the process (returned from an internal GetCurrentProcess() call) to add the callback to the list.

I know this might seem a bit much; but any improvement to even the windows threadig API that allows something like this done is a win for me and my projects.

**Comment by samtertzakian** [comment]
Hi,

This forum is not the correct place for this query. Your query is non-DMF specific. I think you can get better help if you post here:

https://social.msdn.microsoft.com/forums/office/en-us/home?forum=accessdev
