### ISSUE TITLE
DmfModuleId.h does not exist

### ISSUE THREAD

**Issue by hansmbakker** [microsoft/DMF#91]
While creating a new module, I tried following the steps in `Dmf_Template.c`.

However, this line
https://github.com/microsoft/DMF/blob/465ecb1953eea0024c98b821b280a6eed2f05223/Dmf/Modules.Template/Dmf_Template.c#L20

is unclear, since `DmfModuleId.h` does not exist.

Should that be `DmfModules.Template.h`?

**Comment by samtertzakian** [comment]
Hi Hans,

Please ignore that comment. It is an old comment that no longer applies.
So sorry for about that.  I will remove it in the next update this week.

**Comment by hansmbakker** [comment]
That's fine, thanks for the quick response!

**Comment by samtertzakian** [comment]
Corrected in Release LKG 1.1.37.
